title: 23rd Conference on Business Process Management
url: "https://www.bpm2025seville.org"
#baseurl: bpm2025
author: Universidad de Sevilla
description: |
  BPM2025 conference will take place in Seville, Spain.
  
enforce_ssl: "www.bpm2025seville.org"
relative_permalinks: false
permalink: news/:title/ # permalink: date
timezone: Europe/Madrid
conf_year: 2025

include:
  - _pages

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .cache
  - .editorconfig
  - .gitignore
  - .vendor
  - bin
  - bower_components
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docker-compose.yml
  - EDITORS_GUIDE.md
  - Gemfile
  - Gemfile.lock
  - justfile
  - LICENSE
  - Makefile
  - node_modules
  - NOTES.md
  - package*.json
  - Procfile
  - Rakefile
  - README.md
  - vendor
  - webpack.config.js

# We need `future` to allow our schedule to work :/
future: true

collections: # process the _data folder
  components:
    output: false
  organisers:
    output: false
    permalink: /:collection/
  news:
    output: false
    permalink: /:collection/
  incomings:
    output: false
    permalink: /:collection/
  sponsors:
    output: false
    permalink: /:collection/
  stayings:
    output: false
    permalink: /:collection/
  steerings:
    output: false
    permalink: /:collection/
  visas:
    output: false
    permalink: /:collection/

# SEO Plugin settings

twitter:
  username: bpmconf

# This is the default logo that people see with opengraph
# logo: /static/2023-logos/squares-and-social/djangocon-square.png
logo: /static/image/logo.png

# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/image/logo.png

# Emails
conduct_email: "info@bpm2025seville.org"
contact_us_email: "info@bpm2025seville.org"
content_email: "info@bpm2025seville.org"
sponsors_email: "info@bpm2025seville.org"

# Links
cfp_application: "https://easychair.org/"
#opportunity_grant_application: "https://forms.gle/3HCUj3CNzBzwsbdw5"
#discord_link: ""
# slack_link: "https://join.slack.com/t/djangoconeurope/shared_invite/zt-1gjg5lqkz-qVQkNnhjztXVme7TQ7ziQA"
#sponsorship_prospectus: ""
#ticket_link: "https://pretix.eu/puksl/dceu2023"
#schedule_link: "https://pretalx.com/djangocon-europe-2023/schedule"

#github: [metadata]
