name: Deploy to GitHub Pages 🚀

on:
  push:
    branches: 
      - master
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build 🏗️
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci

      - name: Build 🏗️
        env:
          STAGING: 1
          BASE_URL: /bpm2025
          SITE_URL: https://us-ferferga.github.io
        run: npm run build

      - name: Upload GitHub Pages artifact ⬆️
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist

      - name: Deploy to GitHub Pages 🚀
        id: deploy
        uses: actions/deploy-pages@v4.0.5
